# Generated by Django 3.1.2 on 2020-11-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_userlocations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocations',
            old_name='lon',
            new_name='lng',
        ),
    ]
