# Generated by Django 3.1.2 on 2020-11-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20201107_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLocations',
            new_name='UserLocation',
        ),
    ]
