#### Dockerfile to generate a Docker image for nginx ­ to be used in a GeoDjango project
### Start from the official Nginx image
FROM nginx:latest

RUN apt-get -y update && apt-get -y upgrade

# Get rid of old default file and copy our config so that nginx can pick it up
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.old

COPY nginx.conf /etc/nginx/conf.d

EXPOSE 8080